UPDATE "esti_phase"
SET
  "code" = CASE "code"
    WHEN 'BRIEF' THEN 'INITIATION'
    WHEN 'CONCEPT' THEN 'CONCEPT_DESIGN'
    WHEN 'PRELIMINARY' THEN 'DESIGN_DEVELOPMENT'
    WHEN 'APPROVALS' THEN 'STATUTORY_COORDINATION'
    WHEN 'WORKING_TENDER' THEN 'CONSTRUCTION_DOCUMENTATION'
    WHEN 'CONTRACTOR' THEN 'TENDER_APPOINTMENT'
    WHEN 'CONSTRUCTION' THEN 'CONSTRUCTION_ADMINISTRATION'
    WHEN 'COMPLETION' THEN 'HANDOVER_CLOSEOUT'
    ELSE "code"
  END,
  "label" = CASE "code"
    WHEN 'BRIEF' THEN 'Initiation & Brief'
    WHEN 'CONCEPT' THEN 'Concept Design'
    WHEN 'PRELIMINARY' THEN 'Design Development'
    WHEN 'APPROVALS' THEN 'Statutory Coordination'
    WHEN 'WORKING_TENDER' THEN 'Construction Documentation'
    WHEN 'CONTRACTOR' THEN 'Tender & Appointment'
    WHEN 'CONSTRUCTION' THEN 'Construction Administration'
    WHEN 'COMPLETION' THEN 'Handover & Closeout'
    ELSE "label"
  END,
  "billing_pct" = CASE "code"
    WHEN 'BRIEF' THEN 5
    WHEN 'CONCEPT' THEN 10
    WHEN 'PRELIMINARY' THEN 15
    WHEN 'APPROVALS' THEN 15
    WHEN 'WORKING_TENDER' THEN 20
    WHEN 'CONTRACTOR' THEN 10
    WHEN 'CONSTRUCTION' THEN 20
    WHEN 'COMPLETION' THEN 5
    ELSE "billing_pct"
  END
WHERE "code" IN (
  'BRIEF', 'CONCEPT', 'PRELIMINARY', 'APPROVALS',
  'WORKING_TENDER', 'CONTRACTOR', 'CONSTRUCTION', 'COMPLETION'
);
