#!/bin/bash
# ============================================================
#  ESTI AORMS — One-shot VPS setup script
#  Run on Ubuntu 22.04 / 24.04 as root:
#    bash setup-vps.sh
# ============================================================
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

info()    { echo -e "${GREEN}[✔]${NC} $*"; }
section() { echo -e "\n${CYAN}${BOLD}▶ $*${NC}"; }
warn()    { echo -e "${YELLOW}[!]${NC} $*"; }
error()   { echo -e "${RED}[✘] ERROR:${NC} $*"; exit 1; }
ask()     { echo -en "${BOLD}$1${NC} "; read -r "$2"; }
askpass() { echo -en "${BOLD}$1${NC} "; read -rs "$2"; echo; }

[[ $EUID -ne 0 ]] && error "Run as root: sudo bash setup-vps.sh"

clear
echo -e "${CYAN}${BOLD}"
echo "  ███████╗███████╗████████╗██╗"
echo "  ██╔════╝██╔════╝╚══██╔══╝██║"
echo "  █████╗  ███████╗   ██║   ██║"
echo "  ██╔══╝  ╚════██║   ██║   ██║"
echo "  ███████╗███████║   ██║   ██║"
echo "  ╚══════╝╚══════╝   ╚═╝   ╚═╝"
echo -e "  AORMS — VPS Setup${NC}"
echo "  ============================================"
echo ""

# ── Collect all inputs up front ──────────────────────────────────────────────
section "Configuration"
echo "Please enter the following details. Press Enter to use the default where shown."
echo ""

ask  "Domain name (e.g. aorms.in):"                         DOMAIN
ask  "Your email (for TLS certificate):"                    ADMIN_EMAIL
ask  "Git branch [main]:"                                   GIT_BRANCH
GIT_BRANCH="${GIT_BRANCH:-main}"

echo ""
warn "Database & session secrets"
ask     "PostgreSQL password:"           POSTGRES_PASSWORD
askpass "Session secret [auto-generate]:" SESSION_SECRET
[[ -z "$SESSION_SECRET" ]] && SESSION_SECRET=$(openssl rand -hex 32) && info "Session secret auto-generated."

echo ""
warn "MinIO (built-in S3-compatible storage)"
ask "MinIO root user   [esti-admin]:"  MINIO_USER
MINIO_USER="${MINIO_USER:-esti-admin}"
askpass "MinIO root password (min 8 chars):" MINIO_PASSWORD

echo ""
warn "First owner account for ESTI"
ask     "Owner email:"     OWNER_EMAIL
askpass "Owner password:"  OWNER_PASSWORD
askpass "Demo account password [demo-password]:" DEMO_PASSWORD
DEMO_PASSWORD="${DEMO_PASSWORD:-demo-password}"

echo ""
info "Configuration collected. Starting setup..."

# ── Derived values ────────────────────────────────────────────────────────────
DEPLOY_DIR="/opt/esti"
REPO_URL="https://github.com/HolagundiWorks/esti.git"
DATABASE_URL="postgresql://esti:${POSTGRES_PASSWORD}@esti-db:5432/esti"
REDIS_URL="redis://esti-redis:6379"
S3_ENDPOINT="http://esti-minio:9000"
S3_PUBLIC_ENDPOINT="https://${DOMAIN}/storage"
S3_BUCKET="esti-documents"

# ── 1. System update ──────────────────────────────────────────────────────────
section "System update"
apt-get update -qq
apt-get upgrade -y -qq
apt-get install -y -qq curl git openssl ufw
info "System packages up to date."

# ── 2. Docker ─────────────────────────────────────────────────────────────────
section "Docker"
if ! command -v docker &>/dev/null; then
  curl -fsSL https://get.docker.com | sh
  systemctl enable --now docker
  info "Docker installed: $(docker --version)"
else
  info "Docker already present: $(docker --version)"
fi
docker compose version &>/dev/null || apt-get install -y docker-compose-plugin
info "Docker Compose plugin ready."

# ── 3. nginx + certbot ────────────────────────────────────────────────────────
section "nginx + certbot"
apt-get install -y -qq nginx certbot python3-certbot-nginx
info "nginx and certbot installed."

# ── 4. Firewall ───────────────────────────────────────────────────────────────
section "UFW firewall"
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp   comment 'SSH'
ufw allow 80/tcp   comment 'HTTP'
ufw allow 443/tcp  comment 'HTTPS'
ufw --force enable
info "Firewall configured (22, 80, 443 open)."

# ── 5. Clone repo ─────────────────────────────────────────────────────────────
section "Repository"
if [[ -d "$DEPLOY_DIR/.git" ]]; then
  info "Repo already at $DEPLOY_DIR — pulling latest $GIT_BRANCH..."
  git -C "$DEPLOY_DIR" fetch origin
  git -C "$DEPLOY_DIR" checkout "$GIT_BRANCH"
  git -C "$DEPLOY_DIR" pull origin "$GIT_BRANCH"
else
  info "Cloning to $DEPLOY_DIR..."
  git clone --branch "$GIT_BRANCH" "$REPO_URL" "$DEPLOY_DIR"
fi
cd "$DEPLOY_DIR"

# ── 6. Write .env ─────────────────────────────────────────────────────────────
section ".env file"
cat > "$DEPLOY_DIR/.env" <<EOF
# Generated by setup-vps.sh on $(date -u +"%Y-%m-%d %H:%M UTC")
NODE_ENV=production
BACKEND_PORT=4000
SESSION_SECRET=${SESSION_SECRET}
COOKIE_SECURE=true
ALLOWED_ORIGINS=https://${DOMAIN}

POSTGRES_USER=esti
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=esti
DATABASE_URL=${DATABASE_URL}

REDIS_URL=${REDIS_URL}

S3_ENDPOINT=${S3_ENDPOINT}
S3_PUBLIC_ENDPOINT=${S3_PUBLIC_ENDPOINT}
S3_BUCKET=${S3_BUCKET}
S3_ACCESS_KEY=${MINIO_USER}
S3_SECRET_KEY=${MINIO_PASSWORD}
S3_REGION=ap-south-1

WORKER_JOB_STREAM=esti:jobs
WORKER_GROUP=esti-workers

SEED_OWNER_EMAIL=${OWNER_EMAIL}
SEED_OWNER_NAME=Firm Owner
SEED_OWNER_PASSWORD=${OWNER_PASSWORD}
SEED_DEMO_PASSWORD=${DEMO_PASSWORD}
EOF
chmod 600 "$DEPLOY_DIR/.env"
info ".env written and locked to root-only (600)."

# ── 7. Build images ───────────────────────────────────────────────────────────
section "Docker build (this takes 3–5 minutes)"
docker compose -f compose.prod.yaml build
info "All images built."

# ── 8. Start infrastructure ───────────────────────────────────────────────────
section "Starting database, Redis, MinIO"
docker compose -f compose.prod.yaml up -d esti-db esti-redis esti-minio

echo -n "  Waiting for esti-db to be healthy"
for i in $(seq 1 24); do
  STATUS=$(docker inspect --format='{{.State.Health.Status}}' esti-db 2>/dev/null || echo "starting")
  [[ "$STATUS" == "healthy" ]] && echo "" && break
  echo -n "."
  sleep 5
done
info "Database healthy."

# Create MinIO bucket
info "Creating MinIO bucket '${S3_BUCKET}'..."
sleep 3
docker run --rm --network esti-aorms-prod_esti-network \
  minio/mc:latest sh -c "
    mc alias set local http://esti-minio:9000 '${MINIO_USER}' '${MINIO_PASSWORD}' --quiet &&
    mc mb --ignore-existing local/${S3_BUCKET} &&
    mc anonymous set download local/${S3_BUCKET}
  " 2>/dev/null && info "MinIO bucket ready." || warn "MinIO bucket creation skipped — run manually if needed."

# ── 9. Start backend + worker ─────────────────────────────────────────────────
section "Starting backend and worker"
docker compose -f compose.prod.yaml up -d backend worker
echo -n "  Waiting for backend to start"
for i in $(seq 1 12); do
  sleep 5
  echo -n "."
  CODE=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:4000/health 2>/dev/null || echo "000")
  [[ "$CODE" == "200" ]] && echo "" && break
done
info "Backend running."

# ── 10. Build frontend static files ──────────────────────────────────────────
section "Building frontend"
docker compose -f compose.prod.yaml --profile build-only build frontend
docker create --name esti-fe-tmp esti-frontend:prod
mkdir -p "$DEPLOY_DIR/frontend/dist"
docker cp esti-fe-tmp:/usr/share/nginx/html/. "$DEPLOY_DIR/frontend/dist/"
docker rm esti-fe-tmp
chown -R www-data:www-data "$DEPLOY_DIR/frontend/dist"
info "Frontend built and copied to $DEPLOY_DIR/frontend/dist"

# ── 11. nginx reverse proxy ───────────────────────────────────────────────────
section "nginx configuration"
NGINX_CONF="/etc/nginx/sites-available/esti"
cp "$DEPLOY_DIR/deploy/nginx-proxy.conf" "$NGINX_CONF"
sed -i "s|DOMAIN_PLACEHOLDER|${DOMAIN}|g"       "$NGINX_CONF"
sed -i "s|DEPLOY_DIR_PLACEHOLDER|${DEPLOY_DIR}|g" "$NGINX_CONF"
ln -sf "$NGINX_CONF" /etc/nginx/sites-enabled/esti
rm -f /etc/nginx/sites-enabled/default
nginx -t
systemctl reload nginx
info "nginx configured for ${DOMAIN}."

# ── 12. TLS certificate ───────────────────────────────────────────────────────
section "Let's Encrypt TLS"
certbot --nginx -d "$DOMAIN" \
  --non-interactive --agree-tos \
  -m "$ADMIN_EMAIL" \
  --redirect
systemctl reload nginx
info "TLS certificate issued for https://${DOMAIN}"

# ── 13. Systemd service ───────────────────────────────────────────────────────
section "Systemd auto-start"
cat > /etc/systemd/system/esti.service <<EOF
[Unit]
Description=ESTI AORMS
After=docker.service
Requires=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=${DEPLOY_DIR}
ExecStart=/usr/bin/docker compose -f compose.prod.yaml up -d
ExecStop=/usr/bin/docker compose -f compose.prod.yaml down
TimeoutStartSec=300

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable esti
info "ESTI will auto-start on reboot."

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}============================================${NC}"
echo -e "${GREEN}${BOLD}  ESTI AORMS is live!${NC}"
echo -e "${GREEN}${BOLD}============================================${NC}"
echo ""
echo -e "  URL      : ${BOLD}https://${DOMAIN}${NC}"
echo -e "  Login    : ${BOLD}${OWNER_EMAIL}${NC}"
echo ""
echo "  Running containers:"
docker compose -f "$DEPLOY_DIR/compose.prod.yaml" ps --format "table {{.Name}}\t{{.Status}}" 2>/dev/null
echo ""
echo -e "  To redeploy after updates: ${CYAN}bash ${DEPLOY_DIR}/deploy/deploy.sh${NC}"
echo ""
