/**
 * AUTO-GENERATED by frontend/scripts/sync-wiki-knowledge.mjs
 * Source: frontend/src/content/wiki/*.md — do not edit by hand.
 * Regenerate after wiki changes so ESTI (Ask ESTI + landing AI) stays aligned.
 */

export const WIKI_PRODUCT_KNOWLEDGE = `\
## Official AORMS Wiki (canonical product documentation)

Public URL: https://wiki.aorms.in

### Getting started (wiki.aorms.in/getting-started)

## 1. Create an account

1. Open [aorms.in](https://aorms.in) and choose **Create account** in the rail, or go directly to [aorms.in/login](https://aorms.in/login) and switch to the sign-up tab.
2. Enter your work email and password. Complete the profile fields (name, firm, COA registration where applicable).
3. Confirm your email if prompted. Every new account receives the **full AORMS workspace** and **5 GB** of included cloud storage.

There is **one standard licence** — you do not pick Lite, Pro, or Enterprise. Unlimited staff, clients, and projects are included from day one.

## 2. First sign-in

After sign-in you may be asked to:

- **Set a new password** (if an admin pre-provisioned your account).
- **Complete your workspace profile** — firm name, address, GSTIN, and practice details used on proposals and invoices.

These gates appear once and unblock the full workspace.

## 3. Understand the shell

AORMS uses a fixed **glass rail** (left), a scrolling **stage** (centre), a **taskbar footer** (calculator, launcher, tray), and a **context ActionDock** (bottom-centre) for screen-specific actions.

| Area | What it does |
|------|----------------|
| **Rail** | Module navigation — Studio Intelligence, Projects, Tasks, Library, Finance, and more |
| **Stage** | The active screen — tables, forms, and project detail |
| **ActionDock** | Create, save, and destroy actions for the current screen (replaces scattered page buttons) |
| **Footer** | Calculator, app launcher, notifications tray |

## 4. Your first hour

Recommended order for a new principal or office manager:

1. **Studio Intelligence** (\`/\`) — read the overview KPIs and Action Centre.
2. **Company** — upload your firm logo, confirm GST and address, review storage usage.
3. **Third Parties → Clients** — add one real client and one active project.
4. **Projects → open the project** — create phases, add a drawing register entry, assign one task.
5. **Tasks** (\`/tasks\`) — log attendance-linked work for today.

## 5. Invite your team

1. Go to **Company account** (from the header ID card or \`/company-account\`).
2. Open **Members** and invite colleagues by email. They must sign up first if they do not have an account.
3. Assign **roles** so finance, HR, and project staff see only what they need.

## 6. Where to go next

- **[How to use AORMS](how-to-use-aorms)** — full workflow guide from enquiry to final account.
- **[Estimation and BOQ](estimation-and-boq)** — in-browser measurement and cost management.
- **[Finance and billing](finance-and-billing)** — proposals, GST invoices, reconciliation.
- **[Account and licence](account-and-licence)** — storage, AI usage, and company settings.

## Frequently asked questions

### Do I need to download anything?

No. AORMS runs entirely in the browser at [aorms.in](https://aorms.in). Sign in from any modern desktop or laptop browser.

### How many users can I add?

Unlimited. Pricing is not per-seat. You pay for **additional cloud storage** and **hosted AI usage** beyond the included allowance, or bring your own API key for Ask ESTI and AI Studio.

### Is there a demo?

Yes. Contact [hi@aorms.in](mailto:hi@aorms.in) or use the demo unlock in the footer if your deployment exposes it. Demo data resets nightly (IST).

---

### How to use AORMS (wiki.aorms.in/how-to-use-aorms)

This guide walks through **how an Indian architecture consultancy runs on AORMS** — from the first client enquiry to final billing. All steps happen in the **cloud workspace**; there is no separate desktop product to install.

---

## The four-stage practice workflow

Every commission follows the same spine in AORMS:

| Stage | What happens | Primary modules |
|-------|----------------|-----------------|
| **01 — Enquiry & proposal** | Lead captured, scope defined, COA fee proposal issued | Leads, Office → Proposals |
| **02 — Design & drawings** | Phases, tasks, drawing register, transmittals | Projects, Tasks, Drawings |
| **03 — Approvals & revisions** | Client decisions, revision intelligence, portal trace | Client portal, Decisions, Critical notes |
| **04 — Bill & close** | GST invoices, reconciliation, filing abstracts | Finance → Invoices, Filing |

The sections below expand each stage with **click-level instructions**.

---

## Studio Intelligence — your morning surface

**Route:** \`/\` (home)

Studio Intelligence is the principal's **action-oriented dashboard**, not a decorative KPI wall.

### What you see

- **Overview tab** — merged studio health: leads, projects, fees at risk, team load.
- **Zone tabs** — Lead · Project · Financial · Team · Work · Approval — each with four KPI tiles and a scrolling data table inside the tile.
- **Sidebar** — AI recommendation over the last ten office-log entries.

### Daily routine (5 minutes)

1. Open AORMS and land on **Studio Intelligence**.
2. Scan **Approval** and **Financial** zones for red or yellow states.
3. Open the ranked **Action Centre** items — overdue client approvals, unbilled completed work, blocked tasks.
4. Use **Ask ESTI** (header or AI panel) to explain a specific risk: *"Why is Project X flagged for fee risk?"*

### Tips

- The page **does not scroll** as a whole — each zone's table scrolls inside its tile. Use the rail to jump modules.
- KPI colours map to zone state (healthy, attention, critical) — treat orange as "needs a principal decision today."

---

## Stage 01 — Enquiry and fee proposal

### Capture the lead

1. **Studio Intelligence → Lead** or **Office → Leads** — create a new lead with client name, site location, and enquiry source.
2. Link the lead to an existing **Client** (Third Parties) or create the client record first.
3. When qualified, **convert to project** — the project inherits client and brief context.

### Issue a COA fee proposal

1. Go to **Office → Proposals** (\`/office/proposals\`).
2. **Create proposal** — choose type (fee proposal / scope agreement as applicable).
3. Enter stage-wise fees on the **COA scale**, SAC code, and payment milestones.
4. Route through internal review if your office uses approval workflows.
5. **Send to client** via the client portal or export PDF for email — the proposal stays on the project record.

### Client approval gate

When the client accepts:

1. Open the proposal and set **client approval** status.
2. The project **fee baseline** is locked for billing — later revisions can carry fee impact separately.

---

## Stage 02 — Design, drawings, and delivery

### Set up the project

1. **Projects** (\`/projects\`) — open the project.
2. **Phases** — mirror your design stages (Concept, SD, DD, CD, etc.).
3. **Project Info / Brief** — complete the questionnaire sections so the team shares one brief.
4. **Assignments** — attach staff from **Studio → Team** to the project.

### Tasks and time

1. **Tasks** (\`/tasks\`) — create tasks per phase with classification (billable / non-billable) and work type (design development, technical production, etc.).
2. Set **estimated hours** and **difficulty** for ASPRF scoring.
3. Staff log **attendance** and attribute time to tasks — workload views show overload before deadlines slip.

### Drawing register

1. In the project, open **Drawings**.
2. Register each sheet: number, title, discipline, revision.
3. Issue **transmittals** — numbered, dated, tied to the project (not a loose email attachment).
4. Upload DXF/PDF as your office policy requires; revisions increment on the same register row.

### Site supervision (consultancy)

For site-led commissions:

1. **Site visits**, **inspections**, **progress reports**, **snags**, and **site instructions** live under the project's site modules.
2. Generate PDF reports from recorded visits — status tracks PENDING → READY on the worker.

---

## Stage 03 — Approvals, revisions, and client portal

### Client portal

1. Enable portal access for the client contact (Third Parties → Client → portal invite).
2. The client sees **only their projects** — drawings for approval, fee status, revision requests.
3. Decisions are **dated and attributed** — not screenshots in WhatsApp.

### Revision intelligence

When the client requests a change:

1. Record a **decision** or **revision request** with category (minor / major / critical) and source (client-driven, internal error, technical query, scope change).
2. Attach **fee and time impact** before work proceeds.
3. **Meeting minutes** can feed revision requests — ESTI can draft formal revision text from MOM for client approval.

### Consultant and contractor portals

- **Consultants** — scoped to their engagement; RFIs and issued drawings only.
- **Contractors** — site instructions and drawings for their package; no office-wide access.

---

## Stage 04 — Finance and close-out

### Invoicing

1. **Finance → Invoices** — create GST invoice from completed stages or running account.
2. Line items use your firm SAC; CGST/SGST or IGST per place of supply.
3. Link invoice to proposal milestones where applicable.

### Reconciliation and filing

1. **Finance → Reconcile** — import bank, 26AS, AIS, GSTR files; match entries.
2. **Finance → Filing** — GST/TDS filing abstracts for the accountant.

### Expenses and payroll

- **Office cash book** and **project expenses** for internal costing.
- **Payroll** (if HR enabled) — payslips tied to attendance.

See **[Finance and billing](finance-and-billing)** for detail.

---

## Library — knowledge your office reuses

**Route:** \`/knowledge-bank\` and \`/libraries/*\`

| Library | Purpose |
|---------|---------|
| **Item library** | Materials, labour, items, brands, specifications, recipes |
| **Compliance** | NBC, FAR, setbacks, fire, regulations |
| **Master plans** | PDF/DWG reference uploads |
| **Standards** | Discipline standards with attached files |

Use the library when writing specs, estimates, and compliance checks — one catalogue for the whole firm.

---

## AI Studio and Ask ESTI

### Ask ESTI

- Available from the header AI entry — asks over **your project and office record**.
- Explains risk across fees, revisions, and site progress.
- Configure **BYO API key** in Company → AI for your own OpenAI-compatible endpoint.

### AI Studio

- Plan-gated module for heavier AI workflows (rank and firm settings apply).
- Uses the same BYO-or-hosted model policy.

**Metering:** Hosted AI is billed per usage. With a valid BYO key, hosted inference is not metered for that firm.

---

## Estimation and BOQ (in-browser)

BOQ and measurement run **inside AORMS** on the project — not a separate Windows app.

1. Open a project → **Estimation** (or Cost / BOQ module as labelled in your build).
2. Build or import a **structure model**, take off quantities, link **rate books** (e.g. CPWD pack).
3. Materials, items, and **bar bending schedules** derive from the same model.
4. Export BOQ/PDF through the worker when ready.

See **[Estimation and BOQ](estimation-and-boq)**.

---

## Office administration

| Task | Where |
|------|--------|
| Firm profile, logo, GST | **Company** (\`/company\`) |
| Users and roles | **Admin → Users** (firm admin) |
| Storage usage | **Company → settings** |
| Audit trail | **Admin → Audit log** |
| Preferences, password | **Profile → Settings** |

Account-level licence and members: **[Company account](/company-account)** portal.

---

## Role-based access (summary)

| Role | Typical access |
|------|----------------|
| **Owner / Principal** | Full studio, financials, approvals |
| **Project architect** | Assigned projects, tasks, drawings |
| **Finance** | Invoices, reconcile, filing — not HR unless granted |
| **HR** | Team, payroll, attendance — when \`hrEnabled\` |
| **Client** | Portal only — their projects |
| **Consultant / Contractor** | Scoped portal |

Capabilities are enforced server-side via \`can(role, capability)\` — the UI hides what the role cannot do.

---

## Keyboard and productivity

- **Global search** — header search across projects, clients, documents.
- **Calculator** — footer left; persists as a float.
- **Pomodoro** — footer tray for focus sessions.
- **ActionDock** — centre bottom; primary save/create for the active screen.

---

## Getting help

- **Email:** [hi@aorms.in](mailto:hi@aorms.in)
- **Wiki:** [wiki.aorms.in](https://wiki.aorms.in)
- **Blog:** [aorms.in/blog](https://aorms.in/blog) — practice notes and release context

---

## Frequently asked questions

### Can we run AORMS on our own server?

AORMS is offered as **cloud SaaS** at aorms.in. Contact Holagundi Consulting Works for dedicated deployment discussions.

### Are there different product editions?

No. **One standard AORMS licence** includes the full feature set. You pay for extra storage and hosted AI, or bring your own AI API key.

### Where did the desktop estimator go?

Estimation is **in the browser workspace** on each project. There is no separate AORMS Estimate download.

### How do I delete a workspace?

Company owners manage their organisation in the **account portal**. Platform operators use the licensing console. For account closure, email [hi@aorms.in](mailto:hi@aorms.in).

---

### Estimation and BOQ (wiki.aorms.in/estimation-and-boq)

AORMS includes **project estimation and BOQ** inside the cloud workspace. You do **not** install a separate desktop application — open the project and work in **Estimation**.

---

## Open estimation on a project

1. **Projects** → select the project.
2. Open **Estimation** (or the cost/BOQ tab for your build).
3. The estimation workspace loads the project's structure model, items, and rate book links.

---

## Typical workflow

### 1. Structure and measurement

- Define or import a **structure model** (levels, elements, dimensions).
- Enter dimensions once — **derived quantities** cascade to child items where formulas apply.
- Use measurement tools aligned to architectural quantities (length, area, volume, count).

### 2. Rate book

- Attach a **rate book** — e.g. CPWD 2021 pack shipped with AORMS, or project-specific rates from the Item Library.
- Pick rate items into the BOQ; overrides stay on the project.

### 3. Items and BOQ

- The **items panel** lists BOQ lines with quantity, rate, and amount.
- Group by trade or specification section as your office prefers.
- Preview the BOQ before issuing.

### 4. Materials takeoff

- **Materials** derive from item recipes and takeoff rules.
- Cross-check against the specification catalogue in the Knowledge Bank.

### 5. Bar bending schedule (BBS)

- For RCC items, open the **steel schedule / BBS** panel.
- Enter bar marks, diameters, and shapes — weights compute from standard formulas.
- BBS totals feed the BOQ and material summaries.

### 6. Export and issue

- Generate **PDF** (BOQ, BBS) via the document worker when status shows READY.
- Store exports on the project record — transmittal or issue log as your QA requires.

---

## Link to cost management

Estimated totals inform:

- **Fee proposals** — sanity-check against construction cost for percentage fees.
- **Running accounts** — when site billing modules are active on the commission.
- **Client reporting** — scoped summaries through the portal if you choose to expose them.

---

## Tips for Indian practice

- Load **CPWD** or firm master rates from the Library — avoid retyping DSR year over year.
- Keep **one live model** per project — duplicate only when branching design options.
- Reconcile **steel weights** between BBS and supplier quotes before final tender issue.

---

## Frequently asked questions

### Is there a Windows app for BOQ?

No. Estimation runs in the browser as part of AORMS. Sign in at [aorms.in](https://aorms.in) and open the project.

### Can I use my own rate book?

Yes. Maintain custom items and rates in the **Item Library** and attach them to projects.

### Does ESTICAD still exist?

Drawing takeoff is handled **inside AORMS estimation** on linked drawings. There is no separate ESTICAD desktop companion to install.

---

### Finance and billing (wiki.aorms.in/finance-and-billing)

AORMS finance modules follow **Indian consultancy practice** — COA fee scales, GST, TDS reconciliation, and April–March reporting context.

---

## Fee proposals

**Route:** Office → Proposals (\`/office/proposals\`)

1. Create a **fee proposal** or **scope agreement** on the unified proposal model.
2. Enter stage-wise fees, percentages, or lump sums per COA convention.
3. Track **internal approval** and **client approval** on the same record.
4. Approved proposals become the **billing baseline** for the project.

---

## GST invoicing

**Route:** Finance → Invoices (\`/finance/invoices\`)

1. **Create invoice** — select client, project, and tax profile.
2. Line items use consultancy **SAC codes**; CGST/SGST or IGST from place of supply.
3. Amounts are stored in **paise** internally; the UI formats INR.
4. Issue PDF; track payment status and credit notes as your policy requires.

---

## Reconciliation

**Route:** Finance → Reconcile (\`/finance/reconcile\`)

1. Import **bank statements**, **26AS**, **AIS**, or **GSTR** files (formats supported by the worker).
2. Review suggested matches; confirm or override.
3. Unmatched entries stay flagged for the accountant.

---

## Filing abstracts

**Route:** Finance → Filing (\`/finance/filing\`)

- Generate **GST** and **TDS** filing abstracts for the compliance period.
- Export for your CA or internal review — tied to reconciled data where possible.

---

## Office cash book and project expenses

- **Cash book** — office-level receipts and payments.
- **Project expenses** — attribute costs to projects for internal job costing.

---

## Payroll (optional)

When HR is enabled for your firm:

- **Finance → Payroll** — payslips from attendance and salary structure.
- Requires \`hr:manage\` capability.

---

## Workflow: bill a design stage

1. Confirm the **stage is complete** on the project (tasks/decisions closed).
2. Open **Proposals** — verify the milestone amount for that stage.
3. **Create invoice** for the milestone; attach reference to the proposal line.
4. Send PDF to client; record receipt in reconcile when paid.
5. Studio Intelligence **Financial** zone should return to green for that project.

---

## Frequently asked questions

### Does AORMS file GST returns directly?

AORMS prepares **abstracts and reconciled data** — your CA files through the government portal. Integration depth may expand; check release notes.

### Are fees in rupees or paise?

Display is rupees; storage is integer **paise** for precision.

### Can clients see invoices in the portal?

Expose as your office policy dictates — fee **status** is visible in the client portal; invoice PDFs per your sharing practice.

---

### Account and licence (wiki.aorms.in/account-and-licence)

## One standard licence

AORMS has **no product tiers**. Every active account receives:

- The **full workspace** (projects, finance, HR, portals, AI, estimation, library)
- **Unlimited users**, clients, contractors, consultants, and projects
- **5 GB** included cloud storage

Legacy names (Lite, Pro, Core, Enterprise) are retired — licensing console and account screens show **AORMS Standard** only.

---

## What you pay for

| Meter | Included | Overage |
|-------|----------|---------|
| **Storage** | 5 GB | Per GB-month beyond included |
| **Hosted AI** | Usage-based | Per token/request when not using BYO key |
| **BYO AI key** | — | Your provider cost; AORMS does not meter hosted AI while BYO is active |

View usage in **Company → settings** (storage bar and AI studio settings).

---

## Account portals

| Portal | URL | Purpose |
|--------|-----|---------|
| **Personal account** | \`/account\` | Email, password, AORMS ID, credentials |
| **Company account** | \`/company-account\` | Members, company licence, administration |

Company **owners** invite members, approve joins, and manage the workspace licence key if your deployment uses node activation.

---

## Sign-in and security

- **Email** is canonical (lowercase) across the platform.
- Enable **TOTP** from the account security panel.
- **Portal users** (clients, contractors) use separate login flows at \`/access\`.

---

## Workspace profile gate

Existing users may be prompted once to complete **firm profile** fields (GSTIN, address, COA details) before accessing the workspace. This keeps proposals and invoices consistent.

---

## Storage management

1. Monitor usage in Company settings.
2. **Archive** closed projects to move files off hot storage where archive workflow exists.
3. Purchase additional storage through your account operator or hi@aorms.in.

---

## AI configuration

1. **Company → AI Studio settings** (firm admin).
2. Set **OpenAI-compatible** base URL and API key for BYO.
3. Ask ESTI and AI Studio prefer BYO when configured; fall back to hosted model if unreachable.

---

## Deleting a company workspace

- **Members** can leave via company account.
- **Owners** requesting full workspace deletion should contact [hi@aorms.in](mailto:hi@aorms.in).
- Platform operators can remove organisations from the licensing console (irreversible).

---

## Frequently asked questions

### Do I need a licence key for cloud SaaS?

Cloud accounts at aorms.in are **activated on sign-up**. Self-hosted or node installs may still display a key field — ignore for standard cloud unless support instructs otherwise.

### Can I add accountants without extra seats?

Yes. **Unlimited users** — add finance roles without per-seat fees.

### Where is the pricing page?

[aorms.in/#pricing](https://aorms.in/#pricing) — usage-based storage and AI on top of the included allowance.

---

### AORMS Wiki (wiki.aorms.in/index)

Welcome to the **AORMS Wiki** — the canonical guide for using the Architecture Office Resource Management System.

AORMS is a **single cloud workspace** for Indian architects and interior designers. There is **one standard licence** with unlimited users, clients, contractors, and projects. You sign in at [aorms.in](https://aorms.in/login) in your browser — there are **no desktop apps to install** and **no edition tiers** (Lite, Pro, or Enterprise).

Everything in this wiki assumes you are working in the **browser workspace**. Estimation, BOQ, drawings, finance, and portals all live inside the same account.
`;
